# Generated by Django 5.0.4 on 2024-04-29 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneralSetting',
        ),
    ]
