# Generated by Django 5.0.4 on 2024-05-07 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('order',), 'verbose_name': 'Skill', 'verbose_name_plural': 'Skill'},
        ),
    ]
